// <auto-generated />
namespace WebApplication1.Migrations.PostsDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Like : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Like));
        
        string IMigrationMetadata.Id
        {
            get { return "201507010955531_Like"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
